services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kaspi_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
